# Generated by Django 5.1.7 on 2025-07-20 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_order_orderitem_delete_galleryimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('profile_link', models.URLField()),
                ('hear_about', models.CharField(max_length=50)),
                ('governorate', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('company_website', models.URLField(blank=True)),
                ('company_social', models.URLField()),
                ('ceo_name', models.CharField(max_length=100)),
                ('ceo_phone', models.CharField(max_length=20)),
                ('ceo_email', models.EmailField(max_length=254)),
                ('ceo_id_front', models.FileField(upload_to='ids/corporate/')),
                ('ceo_id_rear', models.FileField(upload_to='ids/corporate/')),
                ('authorized_name', models.CharField(max_length=100)),
                ('authorized_phone', models.CharField(max_length=20)),
                ('authorized_email', models.EmailField(max_length=254)),
                ('authorized_id_front', models.FileField(upload_to='ids/corporate/')),
                ('authorized_id_rear', models.FileField(upload_to='ids/corporate/')),
                ('tax_certificate', models.FileField(upload_to='docs/corporate/')),
                ('commercial_registration', models.FileField(upload_to='docs/corporate/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('profile_link', models.URLField()),
                ('hear_about', models.CharField(max_length=50)),
                ('governorate', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('camera_system', models.CharField(blank=True, max_length=100)),
                ('professional_category', models.CharField(max_length=50)),
                ('portfolio_link', models.URLField()),
                ('id_front', models.FileField(upload_to='ids/individual/')),
                ('id_rear', models.FileField(upload_to='ids/individual/')),
                ('other_id', models.FileField(upload_to='ids/individual/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('profile_link', models.URLField()),
                ('hear_about', models.CharField(max_length=50)),
                ('governorate', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studio_name', models.CharField(max_length=100)),
                ('id_front', models.FileField(upload_to='ids/studio/')),
                ('id_rear', models.FileField(upload_to='ids/studio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
