# Generated by Django 5.1.7 on 2025-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_order_options_corporateprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studioprofile',
            old_name='mobile_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='studioprofile',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='building',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='hear_about',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='id_rear',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='profile_link',
        ),
        migrations.RemoveField(
            model_name='studioprofile',
            name='street',
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
        ),
    ]
