# Generated by Django 5.1.7 on 2025-07-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rename_mobile_phone_studioprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateprofile',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='camera_system',
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='hear_about',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='profile_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='authorized_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='authorized_id_front',
            field=models.FileField(blank=True, null=True, upload_to='ids/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='authorized_id_rear',
            field=models.FileField(blank=True, null=True, upload_to='ids/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='authorized_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='authorized_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='ceo_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='ceo_id_front',
            field=models.FileField(blank=True, null=True, upload_to='ids/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='ceo_id_rear',
            field=models.FileField(blank=True, null=True, upload_to='ids/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='ceo_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='commercial_registration',
            field=models.FileField(blank=True, null=True, upload_to='docs/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='company_social',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='hear_about',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='profile_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='docs/corporate/'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='hear_about',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='ids/individual/'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='id_rear',
            field=models.FileField(blank=True, null=True, upload_to='ids/individual/'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='other_id',
            field=models.FileField(blank=True, null=True, upload_to='ids/individual/'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='professional_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='profile_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studioprofile',
            name='email',
            field=models.EmailField(blank=True, default='temp@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='studioprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studioprofile',
            name='studio_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studioprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
